### PR TITLE
Adding string tests

### PR DESCRIPTION
**Pull request by MichaelS11**
After https://github.com/mattn/go-oci8/pull/274

### CODE REVIEW

**Comment by MichaelS11** [comment]
FYI, been trying to figure out OCI string binds to get string length back. Have tried a handful of ways and nothing seems to be working yet.

**Comment by djadala** [comment]
> FYI, been trying to figure out OCI string binds to get string length back. Have tried a handful of ways  and nothing seems to be working yet.

do you speaking for output parameters ?
to get back string len, bind it as   C.SQLT_STR  (only if this is output parameter) // N+1 character NULL terminated string 
and set *cdata to 0 ('\0')

**Comment by MichaelS11** [comment]
That gets you back a null terminated string. How do you get the length back, regardless of what kind of string is used?

**Comment by djadala** [comment]
gostring = C.GoString((*C.char)(col.pbuf))

**Comment by djadala** [comment]
because it is null terminated, you cat find this 0 and calculate len
limitation is that you returned string cant contain 0 character

**Comment by MichaelS11** [comment]
Exactly, which brings me back to how does one get the string length back regardless of what kind of string is used?

**Comment by djadala** [comment]
Ok, now i understood you question.
dont know if this help you, but just discover in oracle docs:

Output
Specify the desired length for the return value in the value_sz parameter of the OCIDefineByPos() call, or the value_sz parameter of OCIBindByName() or OCIBindByPos() for PL/SQL blocks. If zero is specified for the length, no data is returned.

If you omit the rlenp parameter of OCIDefineByPos(), returned values are blank-padded to the buffer length, and NULLs are returned as a string of blank characters. If rlenp is included, returned values are not blank-padded. Instead, their actual lengths are returned in the rlenp parameter.

To check if a NULL is returned or if character truncation has occurred, include an indicator parameter in the OCIDefineByPos() call. Oracle sets the indicator parameter to -1 when a NULL is fetched and to the original column length when the returned value is truncated. Otherwise, it is set to zero. If you do not specify an indicator parameter and a NULL is selected, the fetch call returns the error code OCI_SUCCESS_WITH_INFO. Retrieving diagnostic information on the error will return ORA-1405.

**Comment by djadala** [comment]
>If you omit the rlenp parameter of OCIDefineByPos(), returned values are blank-padded to the buffer >length, and NULLs are returned as a string of blank characters. If rlenp is included, returned values >are not blank-padded. Instead, their actual lengths are returned in the rlenp parameter.


so this seem easy, with 1 more variable in oci8bind struct

**Comment by MichaelS11** [comment]
@djadala Thank you, looking into this.

**Comment by MichaelS11** [comment]
@djadala 

I tried using alenp, it gives me the max length 32767. Had the same issue when using OCIBindDynamic. Not sure what I am doing wrong.

Here is the code if you want to look at it, work in progress, don't mind the mess.

https://github.com/MichaelS11/go-oci8/tree/temp

**Comment by djadala** [comment]
it works for me !
now i post here short instructions,
because i work very old version of this driver, and i made some changes so it diverged from original.
i need some time to bring my version in sync, but until that here are instructions:

1 add to struct oci8bind  alen pionter:
```go
type oci8bind struct {
	kind C.ub2
	alen *C.ub2
	pbuf unsafe.Pointer
	out  interface{} // original binded data type
}
```
2 in bind function, allocate 2 bytes, and set value to actual string len:
```go
		s.pbind[i].alen = (*C.ub2)(C.malloc(2))
		*s.pbind[i].alen = 0 //(C.ub2)(clen)
		if rv := C.OCIBindByPos(
			(*C.OCIStmt)(s.s),
			s.bp,
			(*C.OCIError)(s.c.err),
			C.ub4(i+1),
			unsafe.Pointer(cdata),
			clen,
			dty,
			nil,
			// nil,
			s.pbind[i].alen,
			nil,
			0,
			nil,
			C.OCI_DEFAULT); rv != C.OCI_SUCCESS {
			defer freeBoundParameters(s.pbind)
			return nil, ociGetError(rv, s.c.err)
		}
```
as i understand, in this case clen is total buffer size, and alen is actual string size, so one can pass small input string, and then receive larger output string.
for output parameters, i suggest clen to be set (and allocated) to 4000 - max oracle varchar  len.


3 in outputBoundParameters:
```go
			switch v := col.out.(type) {
			case *string:
				*v = string((*[1 << 24]byte)(col.pbuf)[0:*col.alen])
```

4 don't forget to free alen in freeBoundParameters

Regards

**Comment by MichaelS11** [comment]
@djadala 

Could you look at the code in https://github.com/MichaelS11/go-oci8/tree/temp ?

https://github.com/MichaelS11/go-oci8/blob/temp/statement.go#L207-L214

https://github.com/MichaelS11/go-oci8/blob/temp/statement.go#L836-L855

**Comment by djadala** [comment]
https://github.com/MichaelS11/go-oci8/blob/1a41cdbd8af0c42b7aa4bdcd206aaec18244fa9d/statement.go#L207

you are getting 32767 because binding is  SQLT_AFC,  it always expand string with spaces. try using SQLT_CHR.  I use SQLT_AFC for input strings  because SQLT_CHR trim trailing spaces, if you pass ' '(1 space), it is trimmed to '' and this is converted to NULL, using SQLT_AFC for input strings ensure that they are preserved exactly.
But for output strings, things are different. you can use even SQLT_STR (nul terminated string),  because  OCIBindByPos set correctly alen, and you use it to determine string len.

**Comment by MichaelS11** [comment]
@djadala 

Thank you very much for your help. Been going crazy trying to figure this out. Think I got it working correctly now.

**Comment by MichaelS11** [comment]
@mattn 

My apologies for the large PRs. They should be ready to go.

Please let me know if there are any questions or concerns.

**Comment by mattn** [comment]
LGTM

**Comment by mattn** [comment]
Thanks!

**Pull request merged**
