### PR TITLE
Remove leftovers and unneeded. Added context to bindValues and query.

### PR DESCRIPTION
**Pull request by MichaelS11**
Remove leftovers from Go 1.7 and before
Remove unneeded Exec and Query from conn
Added TestSelectDualNumberScan
Added CheckNamedValue

### CODE REVIEW

**Comment by MichaelS11** [comment]
Created PR for visibility. Work in progress, do not merge.

**Comment by MichaelS11** [comment]
@mattn Good to merge

Any thoughts on how to get an Oracle test image?

**Comment by MichaelS11** [comment]
@mattn Good to merge

**Comment by mattn** [comment]
Thank you

**Pull request merged**
