### PR TITLE
Default timestamp (without time zone) to UTC & Remove select DB time zone

### PR DESCRIPTION
**Pull request by MichaelS11**
Inserting a timestamp (without time zone) just truncates the time zone from timestamp with time zone. So the previous PR does not work.

Changed default time zone to UTC.

@mattn Please create version 0.0.2 and delete broken version 0.0.1.

### CODE REVIEW

**Comment by MichaelS11** [comment]
@mattn ?

**Comment by mattn** [comment]
LGTM

**Comment by mattn** [comment]
Thank you

**Comment by MichaelS11** [comment]
Thank you @mattn 
Could you set this to version 0.0.1 ?

**Comment by mattn** [comment]
okay, I'll release v0.0.2.

**Pull request merged**
