### PR TITLE
Avoid unclosed sockets while opening connections

### PR DESCRIPTION
**Pull request by oserde**
When connections could not be properly established (e.g. wrong password, database in maintenance, etc.) they were not being closed. This might be dangerous when making lots of connections, as the number of sockets (and hence the number of open files) pile up.

### CODE REVIEW

**Comment by MichaelS11** [comment]
@oserde I believe the Go SQL code handles this. Do you have test code showing otherwise?

**Comment by oserde** [comment]
Hi @MichaelS11 . Thank you for your quick response.

I have been using this code for debugging:

```
package main

import (
	"database/sql"
	"fmt"
	"github.com/mattn/go-oci8"
	"log"
	"os"
	"time"
)

func main() {

	oci8.OCI8Driver.Logger = log.New(os.Stderr, "oci8 ", log.Ldate|log.Ltime|log.LUTC|log.Llongfile)

	db, err := sql.Open("oci8", "myuser/mypass@mydb:1527/xxx")
	if err != nil {
		fmt.Printf("Open error is not nil: %v", err)
		return
	}
	if db == nil {
		fmt.Println("db is nil")
		return
	}

	err = db.Ping()
	if err != nil {
		fmt.Printf("Error: %v", err)
		time.Sleep(time.Minute * 10)
		return
	}
}
```
Using a wrong password makes the Ping() call to throw an error. I put the Sleep() call to be able to check open sockets by the process. I have also checked tcp connections. The connection is not closed. In fact, it remains as ESTABLISHED. Eventually the server sends an RST packet due to inactivity. But the socket remains there.

I tried to use db.Close(), but it is useless in this case, because when it gets to [this line](https://github.com/golang/go/blob/master/src/database/sql/sql.go#L820) , variable _db.freeConn_ is empty, and no sockets are closed.

So this PR intends to fix two problems:
1. Sockets might not be closed after a failed connection.
2. Even though we wanted to fix this behaviour externally and call db.close() when Ping() throws an error, this call to db.Close() is unable to close the sockets, because the connection is not inside _db.freeConn_.

Do you think this behaviour should be implemented by go database/sql library?

Thank you.

**Comment by MichaelS11** [comment]
I suggest making the following changes to your test. Move the test code into a function but leave the sleep in the main. Before the Ping add `defer db.Close()`. In oci8 connection.go Close function add a print/log line at the start of the function, really check Close gets called. I am thinking it will but it is very important to know for sure to track down what is going on.

**Comment by MichaelS11** [comment]
See the issue, working on it.

**Comment by MichaelS11** [comment]
Should be fixed in https://github.com/mattn/go-oci8/pull/339
Please test

**Comment by MichaelS11** [comment]
@oserde Please close this PR if https://github.com/mattn/go-oci8/pull/339 fix the issue.

**Comment by oserde** [comment]
Hi @MichaelS11 . PR #339 definitely fixes the issue. Thank you!

Closing in favor of #399

**Pull request closed without merging**
