### PR TITLE
parse environment once, partial modified copy of net/url

### PR DESCRIPTION
**Pull request by djadala**
Regards

### CODE REVIEW

**Comment by mattn** [comment]
Wow, prefetch_rows look nice.

**Comment by djadala** [comment]
Hi,

I specially get them from environment to preserve old behavior.
prefetch_rows && prefetch_memory are currently get from environment at oci.go:1500

I just add option to set them per connection

**Comment by mattn** [comment]
Okay, do you mind that I'll remove them?

**Comment by djadala** [comment]
Ok, i removed them

**Comment by mattn** [comment]
Thanks!

**Pull request merged**
