### PR TITLE
Two-phase commit - XA transaction support

### PR DESCRIPTION
**Pull request by endurox-dev**
Added support for XA transactions. When doing sql.Open("oci8", ""); i.e. with out connection string, the driver will try to acquire connection string from Oracle OCI XA subsystem. The example use can be seen here: https://github.com/endurox-dev/endurox-go/blob/master/tests/04_distributed_transaction/src/server/server.go

The XA sub-system is initialized by Enduro/X, and later by this patch it can be efficiently used in Go programs.

### CODE REVIEW

**Comment by mattn** [comment]
Maybe, it need to use `#ifdef`.

**Comment by endurox-dev** [comment]
Hm only needs to understand how to efficiently enable/disable that macros when user installs the oci driver. Any ideas? Can we at "go get" pass paramters?

**Comment by endurox-dev** [comment]
Tried to use go build -gccgoflags=-DXXXXX but seems to have no effect.

**Comment by mattn** [comment]
As far as I see the some informations in the web, xaoEnv seems fail to link on some environment.

**Comment by endurox-dev** [comment]
Hmm seems this works:

$ cat x.go
package main
/*

#include <stdio.h>

#ifdef TEST1
void test_print(void) {
  printf("TEST1 defined...\n");

}

#else

void test_print(void) {
  printf("TEST1 not defined...\n");

}

#endif

*/
import "C"

func main () {
    C.test_print()
}

$ CGO_CFLAGS="-DTEST1" go build x.go
$ ./x
TEST1 defined...
$ CGO_CFLAGS="-DTEST2" go build x.go
$ ./x
TEST1 not defined...


So  I can try to prepare new define variable which would enable XA.  In that case user could do:
$ CGO_CFLAGS="-DOCI8_ENABLE_XA" go get github.com/mattn/go-oci8

And the needed code blocks will be actived in C side.

**Comment by endurox-dev** [comment]
Hi,

Just updated pull request, with new "OCI8_ENABLE_XA" c define so that XA can be enabled only when needed on desired platforms.

Thanks,
Madars

**Comment by mattn** [comment]
Seems to be conflicting code. Could you please rebase to master?

**Pull request closed without merging**
