### PR TITLE
Added uint64 casting for sql.Out{}.

### PR DESCRIPTION
**Pull request by 242617**

### CODE REVIEW

**Comment by mattn** [comment]
please add test.

**Comment by 242617** [comment]
I'm not sure that test will fix travis check.
```
The command ".travis/oracle/install.sh" failed and exited with 9 during .
```

**Comment by mattn** [comment]
Now test script will be fixed.

https://github.com/mattn/go-oci8/pull/199

**Comment by mattn** [comment]
Now you can write test. Please rebase master.

**Comment by mattn** [comment]
I opend new PR https://github.com/mattn/go-oci8/pull/206
Will add tests. Thanks.

**Pull request closed without merging**
