### PR TITLE
Added OCIHandleFree

### PR DESCRIPTION
**Pull request by MichaelS11**

### CODE REVIEW

**Comment by MichaelS11** [comment]
Welcome :) Glad I could help.

Will add some more notes for some of the PRs where it makes sense. Some of the PRs are testing or visual changes.

If there is something in particular, welcome to ask.

This PR is adding OCIHandleFree for open (connections). OCIHandleFree releases C memory to help prevent memory leaks. If this was just C code would definitely need OCIHandleFree, but because Go wraps it not sure if Go cleans it up. So adding just in case Go does not free up the memory.

**Comment by cjbj** [comment]
@MichaelS11 yell out to us at Oracle if you have OCI questions.  Seeing how @anthony-tuininga does things in [ODPI-C](https://github.com/oracle/odpi) may also be useful.

**Comment by MichaelS11** [comment]
Thank you very much :)

**Comment by mattn** [comment]
Thanks

**Comment by bwmarrin** [comment]
Thanks for the added detail @MichaelS11 and thanks for offering to help @cjbj  :)  I'd love to see this be the best Oracle lib out there.  I'm biased though because I've got a project where I have to do a ton of database work with Oracle and I want to do it all in Go!

**Comment by cjbj** [comment]
@bwmarrin as a serious question, so we (Oracle) can tell what features are important and where to focus, what lead you to choose mattn/go-oci8 over go-goracle/goracle (or even rana/ora)?

**Comment by bwmarrin** [comment]
I've used (and made a minor contribution) to mattn's sqlite library.  So I just tried his Oracle library first and it worked, so I haven't had a reason yet to try the others.  Granted I'm still fairly early on in my project so I'm not sure if I'll run into any issues as things progress.  If so, I've no doubt this library has the support to get them addressed :) 

So, in short, I guess due to familiarity with @mattn himself.

If I run into issues or "wish it had" type of things I'm happy to report back and share my thoughts.

**Comment by cjbj** [comment]
@bwmarrin those are all valid points. Thanks for sharing.

**Pull request merged**
