### PR TITLE
Add ociBreak to Ping

### PR DESCRIPTION
**Pull request by MichaelS11**
@mattn Please review. Not able to create a good test case for this change.

Welcome to merge if change is good.

### CODE REVIEW

**Comment by MichaelS11** [comment]
@mattn Any thoughts?

**Comment by mattn** [comment]
I don't make sure but we have better to add `time.After` to make timeout?

**Comment by MichaelS11** [comment]
Not sure I follow, `time.After` instead of what code?

**Comment by mattn** [comment]
I'm not sure. Do you think Ping timeout is not required?

**Comment by MichaelS11** [comment]
The ctx should provide the timeout for ping using ociBreak.

**Comment by mattn** [comment]
You are right.

**Comment by mattn** [comment]
Thank you

**Pull request merged**
