### PR TITLE
remove usage of finalizers

### LINKED ISSUE #94: Please remove use of SetFinalizers
Hi Mattn,
usage of SetFinalizer in go-oci8 are incorrect, from  runtime.SetFinalizer documentation:
> The argument f must be a function that takes a single argument to which x's type can be assigned

I don't  noticed this error because i have & use my internal version of  of oci8 driver without  using SetFinalizer.

I open this issue to settle what you want,  i can make PR with SetFinalizer corrected, but prefer to remove them.
finalizers   are useless there, user must always close connections & statements, and those Close functions in go-oci8 are not functions that user call in sql package.
What is your opinion ?

### PR DESCRIPTION
**Pull request by djadala**
Fixes #94

### CODE REVIEW

**Comment by mattn** [comment]
I'm still having confusing. How about this change?

```diff
diff --git a/oci8.go b/oci8.go
index 2f22bf9..d6d2a3d 100644
--- a/oci8.go
+++ b/oci8.go
@@ -346,6 +346,7 @@ type OCI8Conn struct {
 	transactionMode      C.ub4
 	inTransaction        bool
 	enableQMPlaceholders bool
+	closed               bool
 }
 
 type OCI8Tx struct {
@@ -561,6 +562,11 @@ func (d *OCI8Driver) Open(dsnString string) (connection driver.Conn, err error)
 }
 
 func (c *OCI8Conn) Close() error {
+	if c.closed {
+		return nil
+	}
+	c.closed = true
+
 	var err error
 	if rv := C.OCILogoff(
 		(*C.OCISvcCtx)(c.svc),
@@ -1076,7 +1082,7 @@ func (s *OCI8Stmt) Query(args []driver.Value) (rows driver.Rows, err error) {
 			return nil, ociGetError(rv, s.c.err)
 		}
 	}
-	return &OCI8Rows{s, oci8cols, false, indrlenptr}, nil
+	return &OCI8Rows{s, oci8cols, false, indrlenptr, false}, nil
 }
 
 // OCI_ATTR_ROWID must be get in handle -> alloc
@@ -1185,6 +1191,7 @@ type OCI8Rows struct {
 	cols       []oci8col
 	e          bool
 	indrlenptr unsafe.Pointer
+	closed     bool
 }
 
 func freeDecriptor(p unsafe.Pointer, dtype C.ub4) {
@@ -1193,6 +1200,11 @@ func freeDecriptor(p unsafe.Pointer, dtype C.ub4) {
 }
 
 func (rc *OCI8Rows) Close() error {
+	if rc.closed {
+		return nil
+	}
+	rc.closed = true
+
 	C.free(rc.indrlenptr)
 	for _, col := range rc.cols {
 		switch col.kind {
```

**Comment by djadala** [comment]
Hm, I'm also confused, that are not changes i made
please see https://github.com/djadala/go-oci8/commit/9c88d421c88be535cc0e602404de05afeef82000

**Comment by djadala** [comment]
changes are:
```go
@@ -309,7 +309,6 @@ import (
  	"io"
  	"math"
  	"regexp"
 -	"runtime"
  	"strconv"
  	"strings"
  	"time"
 @@ -555,9 +554,7 @@ func (d *OCI8Driver) Open(dsnString string) (connection driver.Conn, err error)
  	conn.prefetch_rows = dsn.prefetch_rows
  	conn.prefetch_memory = dsn.prefetch_memory
  	conn.enableQMPlaceholders = dsn.enableQMPlaceholders
 -	c := &conn
 -	runtime.SetFinalizer(c, (*OCI8Conn).Close)
 -	return c, nil
 +	return &conn, nil
  }
  
  func (c *OCI8Conn) Close() error {
 @@ -575,7 +572,6 @@ func (c *OCI8Conn) Close() error {
  	c.svc = nil
  	c.env = nil
  	c.err = nil
 -	runtime.SetFinalizer(c, nil)
  	return err
  }
  
 @@ -616,9 +612,7 @@ func (c *OCI8Conn) Prepare(query string) (driver.Stmt, error) {
  		return nil, ociGetError(rv, c.err)
  	}
  
 -	ss := &OCI8Stmt{c: c, s: s, bp: (**C.OCIBind)(bp), defp: (**C.OCIDefine)(defp)}
 -	runtime.SetFinalizer(ss, (*OCI8Stmt).Close)
 -	return ss, nil
 +	return &OCI8Stmt{c: c, s: s, bp: (**C.OCIBind)(bp), defp: (**C.OCIDefine)(defp)}, nil
  }
  
  func (s *OCI8Stmt) Close() error {
 @@ -631,7 +625,6 @@ func (s *OCI8Stmt) Close() error {
  		s.s,
  		C.OCI_HTYPE_STMT)
  	s.s = nil
 -	runtime.SetFinalizer(s, nil)
  	return nil
  }
 
```

**Comment by mattn** [comment]
Yes, I understand. I wonder why SetFinalizer doesn't work. When user forgot to Close(), this is useful to  close automatically, I thought.

**Comment by djadala** [comment]
When you forgot to close, you are not closing instances of sql.DB. actual oci8.OCI8Driver struct are always refferenced by pool of connections in sql package.

**Comment by mattn** [comment]
Okay, I'll merge this. But I wonder why go-sqlite3 works well.

https://github.com/mattn/go-sqlite3/blob/master/sqlite3.go#L711-L720

**Pull request merged**
