### PR TITLE
Handle OCI_SUCCESS_WITH_INFO on Pings

### PR DESCRIPTION
**Pull request by stampy88**
- OCI_SUCCESS_WITH_INFO was causing errors on pings

### CODE REVIEW

**Comment by MichaelS11** [comment]
@mattn Seems fine with me.

**Comment by MichaelS11** [comment]
@mattn Side note, looks like wnameless/oracle-xe-11g was removed. I assume Oracle is going after sites and removing these images?

**Comment by stampy88** [comment]
It looks like there may be more cases where this fails too. I am going to include them as well in few minutes.

**Comment by stampy88** [comment]
@mattn I think this brings up a bigger question: is there anytime where you **would** want `OCI_SUCCESS_WITH_INFO` to be handled as an **error** and not success? Looking through the code base there are lots of checks for `OCI_SUCCESS`.

**Comment by stampy88** [comment]
Added checking in the `OCI8DriverStruct.Open` as well, and that got me working, e.g. selects, updates, inserts, deletes. My original question above still stands though. This may be something that should be tackled across the project.

**Comment by mattn** [comment]
@MichaelS11 

>Side note, looks like wnameless/oracle-xe-11g was removed. I assume Oracle is going after sites and removing these images?

Hmm, I have no idea. :(

>I think this brings up a bigger question: is there anytime where you would want OCI_SUCCESS_WITH_INFO to be handled as an error and not success? Looking through the code base there are lots of checks for OCI_SUCCESS.

Yes, I think so.

**Comment by MichaelS11** [comment]
I probably would not add OCI_SUCCESS_WITH_INFO to everything. Honestly would really like to understand more why it is happening for the 3 locations so far in this PR. 

That being said, I am fine with changing the 3 locations to have OCI_SUCCESS_WITH_INFO, just would not add any more at this time.

**Comment by stampy88** [comment]
@MichaelS11 I was hoping you guys could give a better idea why it is only needed in those 3 places. And honestly, it is only needed in 2 of the 3 since this is always true 

https://github.com/mattn/go-oci8/blob/master/oci8.go#L245

I won't add anymore, so merge away if you guys are happy.

**Comment by stampy88** [comment]
@MichaelS11 any more thoughts on this?

**Comment by MichaelS11** [comment]
Was curious, do you know of any test cases for these?

**Comment by stampy88** [comment]
The way I happened to see this was that we spun up a new DB, but that password was set to expire after a certain period. Once we got close to the expiration date, a warning started coming back and the code wasn't handling it.

**Comment by MichaelS11** [comment]
Ah, I see now. Got it.

@mattn Looks good to me.

**Comment by mattn** [comment]
Thank you

**Pull request merged**
