### PR TITLE
Added prefetch_lob_size

### PR DESCRIPTION
**Pull request by MichaelS11**

### CODE REVIEW

**Comment by MichaelS11** [comment]
@mattn 

docker pull failed

```
0.62s$ docker pull alexeiled/docker-oracle-xe-11g 2>&1 > /dev/null
Error response from daemon: pull access denied for alexeiled/docker-oracle-xe-11g, repository does not exist or may require 'docker login'
The command "docker pull alexeiled/docker-oracle-xe-11g 2>&1 > /dev/null" failed and exited with 1 during .
```

**Comment by mattn** [comment]
Hmm, still trying which docker image can be used alternatively. However why the previous was removed.

**Comment by MichaelS11** [comment]
@mattn What about https://hub.docker.com/r/wnameless/oracle-xe-11g ?

**Comment by mattn** [comment]
Could you please try it with modifying .travis.yml?

**Pull request closed without merging**
