### PR TITLE
Two-phase commit - XA distributed transaction processing option

### PR DESCRIPTION
**Pull request by endurox-dev**
Hi, 

I have merged my changes with your latest development. Both modes tested (normal and XA) works ok. I have closed previous pull request, so this is actual now.

Thanks,
Madars

### CODE REVIEW

**Comment by mattn** [comment]
LGTM but please wait when I'll check this on linux and windows both.

**Comment by endurox-dev** [comment]
Any news about this?

**Comment by mattn** [comment]
Sorry delays. This is my wrong. Could you please make diff again from master branch?

May be simply https://github.com/mattn/go-oci8/pull/108/commits/715663430ec951a2a64ef979973a30d7ad22520b ?

**Comment by endurox-dev** [comment]
Create new pull request, merged both masters. Should integrate with no problems: https://github.com/mattn/go-oci8/pull/174

**Pull request closed without merging**
