### PR TITLE
Double max size buffer for strings

### PR DESCRIPTION
**Pull request by MichaelS11**
https://github.com/mattn/go-oci8/issues/306

### CODE REVIEW

**Comment by MichaelS11** [comment]
Waiting for confirmation from https://github.com/mattn/go-oci8/issues/306

**Comment by cjbj** [comment]
12.2 has OCI_ATTR_MAX_CHARSET_RATIO and OCI_ATTR_MAX_NCHARSET_RATIO to help in these situations.

**Comment by MichaelS11** [comment]
Thank you @cjbj , good to know. Will look to add that in later.

**Comment by MichaelS11** [comment]
@mattn Still good to merge.

**Comment by MichaelS11** [comment]
@mattn Can you merge this?

**Comment by MichaelS11** [comment]
@mattn ?

**Comment by mattn** [comment]
Sorry. Thanks!

**Pull request merged**
