### PR TITLE
Use XE in Travis CI

### PR DESCRIPTION
**Pull request by cbandy**
This is a slimmer alternative to #61.

- The XE install includes a full client so there's no need to install anything else.
- `.travis/oracle` is a clean install of [cbandy/travis-oracle](https://github.com/cbandy/travis-oracle) so there will be no issues updating to future versions.
- Secure variables can be set [directly in Travis CI](http://docs.travis-ci.com/user/environment-variables/#Using-Settings) so there's no need to bother with encryption in `.travis.yml`.

As @jonlawlor pointed out in #60, there is [one failing test](https://travis-ci.org/cbandy/go-oci8/builds/64204796#L324-L327):

```
--- FAIL: TestFooRowid (0.12s)
	more_test.go:112: no row returned: <nil>
```

### CODE REVIEW

**Comment by mattn** [comment]
cc @jonlawlor

**Comment by jonlawlor** [comment]
Nice!  I couldn't get the XE to work for some reason; this is definitely a better approach.  Also, I thought that only paying clients were allowed to use secure environment variables from their web interface.  Either I was mistaken or they changed it, but either way this approach is better than #61.  Would you like me to close it?

**Comment by mattn** [comment]
@cbandy well, i don't look what i have to do yet. is there something that i have to modify .travis.yml?

**Comment by jonlawlor** [comment]
I think you need to go to https://login.oracle.com/mysso/signon.jsp and either create an account and log in, or log in via an existing account.

In the travis-ci web interface for the mattn/go-oci8 project, go to settings -> settings, and then press the "Environment Variables" tab.  Press "Add a new variable" and then enter:
name: ORACLE_LOGIN_ssousername 
value: [Your Oracle Login Username]

And do the same for
name: ORACLE_LOGIN_password
value: [Your Oracle Login Password]

Make sure that "Display value in build logs" is set to OFF in both.

Now on oracle.com go to:
http://www.oracle.com/technetwork/database/database-technologies/express-edition/downloads/index.html
and then click the "Accept License Agreement" radio button.

Then you should be all set.

**Comment by mattn** [comment]
done. thank you

**Comment by jonlawlor** [comment]
[Build Status](https://travis-ci.org/mattn/go-oci8) congratulations!

**Pull request merged**
