### PR TITLE
Set default prefetchRows to 0 and prefetchMemory to 4096

### PR DESCRIPTION
**Pull request by MichaelS11**
https://github.com/mattn/go-oci8/issues/38

### CODE REVIEW

**Comment by MichaelS11** [comment]
Good to go

**Comment by MichaelS11** [comment]
@mattn Travis just needs a restart for it to pass.

**Comment by mattn** [comment]
Hmm, test on travis is flaky

**Comment by MichaelS11** [comment]
Yeah :/

I wonder if it has something to do with alexeiled/docker-oracle-xe-11g, maybe it has bugs in it?

**Comment by MichaelS11** [comment]
@mattn What you think?

**Comment by mattn** [comment]
I hope to wait some consentration for changing prefetchMemory in #38.

**Comment by MichaelS11** [comment]
@mattn FYI will be away from the computer for a couple of weeks. Will not be able to do any code changes.

**Comment by MichaelS11** [comment]
@mattn https://github.com/mattn/go-oci8/issues/38 seems to have no new comments, could this be merged?

**Pull request merged**
